name: dinadrawing
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1  
  intl: ^0.20.2
  confetti: ^0.8.0
  image_picker: ^0.8.7
  google_maps_flutter: ^2.5.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - images/get-started-pg1.png
    - images/get-started-pg2.png
    - images/get-started-pg3.png
    - images/get-started-pg4.png
    - images/get-started-pg5.png
    - images/logo.png
    - images/wheel.png
    - images/blitz.png
    - images/menu-myplans.png
    - images/grid.png
    - images/list.png
    - images/delete.png
    - images/archive.png
    - images/navbar-icons/

    
