name: dinadrawing
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1  
  intl: ^0.20.2
  confetti: ^0.8.0
  image_picker: ^0.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - images/page1.png
    - images/page2.png
    - images/page3.png
    - images/page4.png
    - images/page5.png
    - images/page6.png
    - images/page7.png
    - images/page8.png
    - images/logo.png
    - images/wheel.png
    - images/navbar-icons/
    
