// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvChUIKUchybvceAl6xONWxwrvWAX3i1E',
    appId: '1:465293797166:web:9ec87a9ab9fa06e69bbcbf',
    messagingSenderId: '465293797166',
    projectId: 'dinadrawing-app',
    authDomain: 'dinadrawing-app.firebaseapp.com',
    storageBucket: 'dinadrawing-app.firebasestorage.app',
    measurementId: 'G-CM3855XWP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJhgHUxloSOyjiYW1JoOy-wXdVD68cRXM',
    appId: '1:465293797166:android:922ff884e0e927379bbcbf',
    messagingSenderId: '465293797166',
    projectId: 'dinadrawing-app',
    storageBucket: 'dinadrawing-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbrGntWR7X794_6mXyHSDaFn-CqulB6to',
    appId: '1:465293797166:ios:17592f4fd32946b69bbcbf',
    messagingSenderId: '465293797166',
    projectId: 'dinadrawing-app',
    storageBucket: 'dinadrawing-app.firebasestorage.app',
    iosClientId: '465293797166-3gd0a19fvlake4ovedmak2g1nniuffrr.apps.googleusercontent.com',
    iosBundleId: 'com.example.dinadrawing',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbrGntWR7X794_6mXyHSDaFn-CqulB6to',
    appId: '1:465293797166:ios:17592f4fd32946b69bbcbf',
    messagingSenderId: '465293797166',
    projectId: 'dinadrawing-app',
    storageBucket: 'dinadrawing-app.firebasestorage.app',
    iosClientId: '465293797166-3gd0a19fvlake4ovedmak2g1nniuffrr.apps.googleusercontent.com',
    iosBundleId: 'com.example.dinadrawing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvChUIKUchybvceAl6xONWxwrvWAX3i1E',
    appId: '1:465293797166:web:dcb46ef1c101dad89bbcbf',
    messagingSenderId: '465293797166',
    projectId: 'dinadrawing-app',
    authDomain: 'dinadrawing-app.firebaseapp.com',
    storageBucket: 'dinadrawing-app.firebasestorage.app',
    measurementId: 'G-MGRP30ZJCW',
  );
}
